### ISSUE TITLE
macOS 无法获取磁盘信息

### ISSUE THREAD

**Issue by gxusb** [cppla/ServerStatus#193]
client-psutil.py
无法获取磁盘信息

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/105532932/199495613-17a5e6c7-93ba-4767-9175-c3d1585c4835.png">

```
Exception in thread Thread-5 (_disk_io):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Connecting...
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ljn/Desktop/client-psutil.py", line 214, in _disk_io
    p._before = p.io_counters()
AttributeError: 'Process' object has no attribute 'io_counters'
Authentication successful. Access granted.

You are connecting via: IPv4
```

**Comment by cppla** [comment]
已作兼容性处理，beta.
