### ISSUE TITLE
请求客户端支持alpine

### ISSUE THREAD

**Issue by ANewPassword** [cppla/ServerStatus#214]
由于alpine部分命令与目前支持的发行版参数不一致，且输出格式也不同，导致client-linux.py无法在alpine上正常运行：
```
# python3 /root/client-linux.py
Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4

df: unrecognized option: l
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: df [-PkmhTai] [-B SIZE] [-t TYPE] [FILESYSTEM]...

Print filesystem usage statistics

	-P	POSIX output format
	-k	1024-byte blocks (default)
	-m	1M-byte blocks
	-h	Human readable (e.g. 1K 243M 2G)
	-T	Print filesystem type
	-t TYPE	Print only mounts of this type
	-a	Show all filesystems
	-i	Inodes
	-B SIZE	Blocksize
Caught Exception: Command '['df', '-Tlm', '--total', '-t', 'ext4', '-t', 'ext3', '-t', 'ext2', '-t', 'reiserfs', '-t', 'jfs', '-t', 'ntfs', '-t', 'fat32', '-t', 'btrfs', '-t', 'fuseblk', '-t', 'zfs', '-t', 'simfs', '-t', 'xfs']' returned non-zero exit status 1.

^CTraceback (most recent call last):
  File "/root/client-linux.py", line 379, in <module>
    HDDTotal, HDDUsed = get_hdd()
                        ^^^^^^^^^
  File "/root/client-linux.py", line 58, in get_hdd
    p = subprocess.check_output(['df', '-Tlm', '--total', '-t', 'ext4', '-t', 'ext3', '-t', 'ext2', '-t', 'reiserfs', '-t', 'jfs', '-t', 'ntfs', '-t', 'fat32', '-t', 'btrfs', '-t', 'fuseblk', '-t', 'zfs', '-t', 'simfs', '-t', 'xfs']).decode("Utf-8")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['df', '-Tlm', '--total', '-t', 'ext4', '-t', 'ext3', '-t', 'ext2', '-t', 'reiserfs', '-t', 'jfs', '-t', 'ntfs', '-t', 'fat32', '-t', 'btrfs', '-t', 'fuseblk', '-t', 'zfs', '-t', 'simfs', '-t', 'xfs']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/client-linux.py", line 427, in <module>
    time.sleep(3)
KeyboardInterrupt
```
在将HDDTotal, HDDUsed = get_hdd()临时修改为HDDTotal, HDDUsed = 1, 1后，重新运行又出现新报错：
```
# python3 /root/client-linux.py
Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4

/bin/sh: ss: not found
/bin/sh: ss: not found
ps: unrecognized option: L
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads

^CTraceback (most recent call last):
  File "/root/client-linux.py", line 412, in <module>
    array['tcp'], array['udp'], array['process'], array['thread'] = tupd()
                                                                    ^^^^^^
  File "/root/client-linux.py", line 116, in tupd
    s = subprocess.check_output("ps -eLf|wc -l", shell=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```
在将array['tcp'], array['udp'], array['process'], array['thread'] = tupd()修改为array['tcp'], array['udp'], array['process'], array['thread'] = 1, 1, 1, 1后可以正常运行。

此外，client-psutil.py同样拥有此问题：
```
# python3 /root/client-psutil.py
Connecting...
Authentication successful. Access granted.

You are connecting via: IPv4

/bin/sh: ss: not found
/bin/sh: ss: not found
ps: unrecognized option: L
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads

^CTraceback (most recent call last):
  File "/root/client-psutil.py", line 364, in <module>
    CPU = get_cpu()
          ^^^^^^^^^
  File "/root/client-psutil.py", line 67, in get_cpu
    return psutil.cpu_percent(interval=INTERVAL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/psutil/__init__.py", line 1749, in cpu_percent
    time.sleep(interval)
KeyboardInterrupt
```

**Comment by LiJinChang** [comment]
Alpine 要用 client-psutil.py 客户端，psutil 用 apk add py3-psutil 来安装

**Comment by cppla** [comment]
楼上正解， client-linux无法工作的情况下，请换成client-psutil兼容版。 @ANewPassword A
